'use strict';
const { test } = require('node:test');
const assert = require('node:assert/strict');
const { createAdminApi } = require('../admin-api');

const USERS = {
  owner: { id:'00000000-0000-4000-8000-000000000001',clerkUserId:'owner',name:'Owner',email:'o@example.test',role:'OWNER',accountStatus:'ACTIVE' },
  owner2: { id:'00000000-0000-4000-8000-000000000006',clerkUserId:'owner2',name:'Owner Two',email:'o2@example.test',role:'OWNER',accountStatus:'ACTIVE' },
  admin: { id:'00000000-0000-4000-8000-000000000002',clerkUserId:'admin',name:'Admin',email:'a@example.test',role:'ADMIN',accountStatus:'ACTIVE' },
  dev: { id:'00000000-0000-4000-8000-000000000003',clerkUserId:'dev',name:'Dev',email:'d@example.test',role:'DEVELOPER',accountStatus:'ACTIVE' },
  member: { id:'00000000-0000-4000-8000-000000000004',clerkUserId:'member',name:'Member',email:'m@example.test',role:'MEMBER',accountStatus:'ACTIVE' },
  disabled: { id:'00000000-0000-4000-8000-000000000005',clerkUserId:'disabled',name:'Disabled',email:'x@example.test',role:'ADMIN',accountStatus:'DISABLED' },
};
const makeStore=()=>{const audits=[];return { audits, configured:()=>true,syncUser:async()=>{},getByClerkId:async id=>USERS[id],getUser:async id=>Object.values(USERS).find(u=>u.id===id),listUsers:async()=>({users:Object.values(USERS),total:6}),counts:async()=>({total_users:6,onboarded_users:0,onboarding_last_24h:0}),countOwners:async()=>1,listAudit:async()=>({events:audits,total:audits.length}),health:async()=>({ok:true}),setStatus:async({actor,target,status,requestId})=>{target.accountStatus=status;audits.push({action:'USER_DISABLED',requestId});return {user:target}},setRole:async({target,role,requestId})=>{target.role=role;audits.push({action:'ROLE_CHANGED',requestId});return {user:target}},writeAudit:async event=>audits.push(event)} };
const invoke=async(api,{identity,path,method='GET',body={}})=>{const req={method,headers:{},identity,body};const res={status:null,body:null,headers:{},setHeader(k,v){this.headers[k]=v}};await api.handle(req,res,new URL(`http://local${path}`));return res};
const setup=()=>{const store=makeStore();const api=createAdminApi({enabled:()=>true,authenticate:async req=>req.identity?{id:'local',clerkUserId:req.identity}:null,store,readBody:async req=>req.body,json:(res,status,body)=>{res.status=status;res.body=body},listKeys:async()=>({keys:[{id:'safe',label:'key',prefix:'lians_•••',status:'ACTIVE'}],total:1,available:true}),revokeKey:async id=>id==='safe'?{id,ownerUserId:USERS.member.id}:null,systemStatus:async()=>({websiteApi:{status:'healthy'}})});return {api,store}};

test('admin API rejects unauthenticated, member, and disabled identities',async()=>{for(const identity of [null,'member','disabled']){const {api}=setup();const r=await invoke(api,{identity,path:'/api/admin/session'});assert.equal(r.status,identity?403:401)}});
test('developer can read system but cannot mutate',async()=>{const {api}=setup();assert.equal((await invoke(api,{identity:'dev',path:'/api/admin/system'})).status,200);assert.equal((await invoke(api,{identity:'dev',path:`/api/admin/users/${USERS.member.id}/status`,method:'PATCH',body:{status:'DISABLED'}})).status,403)});
test('admin can change member status but cannot modify owner or grant roles',async()=>{const {api,store}=setup();assert.equal((await invoke(api,{identity:'admin',path:`/api/admin/users/${USERS.member.id}/status`,method:'PATCH',body:{status:'DISABLED',role:'OWNER'}})).status,200);assert.equal(store.audits.length,1);assert.equal((await invoke(api,{identity:'admin',path:`/api/admin/users/${USERS.owner.id}/status`,method:'PATCH',body:{status:'DISABLED'}})).status,403);assert.equal((await invoke(api,{identity:'admin',path:`/api/admin/users/${USERS.member.id}/role`,method:'PATCH',body:{role:'OWNER'}})).status,403)});
test('owner cannot change their own role or remove the last other owner',async()=>{const {api,store}=setup();assert.equal((await invoke(api,{identity:'owner',path:`/api/admin/users/${USERS.owner.id}/role`,method:'PATCH',body:{role:'ADMIN'}})).status,403);assert.equal((await invoke(api,{identity:'owner',path:`/api/admin/users/${USERS.owner2.id}/role`,method:'PATCH',body:{role:'ADMIN'}})).status,409);assert.equal(store.audits.length,0)});
test('key lists are metadata-only and revocation is audited',async()=>{const {api,store}=setup();const list=await invoke(api,{identity:'owner',path:'/api/admin/api-keys'});assert.equal(list.status,200);assert.doesNotMatch(JSON.stringify(list.body),/plaintext|hashedKey|secret-value/);const revoked=await invoke(api,{identity:'owner',path:'/api/admin/api-keys/safe/revoke',method:'POST'});assert.equal(revoked.status,200);assert.equal(store.audits.at(-1).action,'API_KEY_REVOKED')});
test('failed key revocation does not create a success audit',async()=>{const {api,store}=setup();const r=await invoke(api,{identity:'owner',path:'/api/admin/api-keys/missing/revoke',method:'POST'});assert.equal(r.status,404);assert.equal(store.audits.length,0)});
