'use strict';
const { test } = require('node:test');
const assert = require('node:assert/strict');
const { createAdminApi } = require('../admin-api');

const IDs={owner:'00000000-0000-4000-8000-000000000001',admin:'00000000-0000-4000-8000-000000000002',dev:'00000000-0000-4000-8000-000000000003',member:'00000000-0000-4000-8000-000000000004',flag:'20000000-0000-4000-8000-000000000001',tag:'10000000-0000-4000-8000-000000000002'};
const users=Object.fromEntries(Object.entries(IDs).filter(([k])=>['owner','admin','dev','member'].includes(k)).map(([role,id])=>[role,{id,clerkUserId:role,email:`${role}@example.test`,name:role,role:role==='dev'?'DEVELOPER':role.toUpperCase(),accountStatus:'ACTIVE',onboardingComplete:true}]));
const makeStore=()=>{const calls=[];const flag={id:IDs.flag,key:'policy_gate',displayName:'Policy Gate',description:'safe',globalEnabled:false,internalOnly:false};return {calls,configured:()=>true,syncUser:async()=>{},getByClerkId:async id=>users[id],getUser:async id=>Object.values(users).find(u=>u.id===id),listFlags:async()=>[flag],getFlag:async()=>flag,saveFlag:async x=>{calls.push(['flag',x]);return {...flag,globalEnabled:x.globalEnabled}},listFlagOverrides:async()=>[],setFlagOverride:async x=>calls.push(['override',x]),usage:async()=>({api_calls:12,failed_requests:2,rate_limit_hits:1,active_users:3,byType:[{eventType:'api_request',count:12}]}),listErrors:async()=>({events:[{requestId:'req-safe',route:'/api/keys',message:'VALIDATION response',statusCode:400}],total:1}),listNotes:async()=>[],saveNote:async x=>calls.push(['note',x]),listTags:async()=>[{id:IDs.tag,key:'BETA',displayName:'Beta'}],userTags:async()=>[],setUserTag:async x=>calls.push(['tag',x]),listRateLimits:async()=>[],saveRateLimit:async x=>{calls.push(['limit',x]);return '30000000-0000-4000-8000-000000000001'},revokeRateLimit:async()=>true,listAudit:async()=>({events:[],total:0}),counts:async()=>({total_users:4,onboarded_users:4,onboarding_last_24h:0}),health:async()=>({ok:true})}}
const setup=()=>{const store=makeStore();const api=createAdminApi({enabled:()=>true,authenticate:async req=>req.identity?{id:users[req.identity].id,clerkUserId:req.identity}:null,store,readBody:async req=>req.body||{},json:(res,status,body)=>{res.status=status;res.body=body},listKeys:async()=>({keys:[],total:0,available:true}),revokeKey:async()=>null,systemStatus:async()=>({websiteApi:{status:'healthy'}}),environmentStatus:async()=>({database:{status:'configured',required:true}}),buildInfo:async()=>({commitSha:'abc123',adminConsoleEnabled:true})});return {api,store}}
const invoke=async(api,{identity='owner',path,method='GET',body={}})=>{const req={method,headers:{},identity,body};const res={setHeader(){}};await api.handle(req,res,new URL(`http://local${path}`));return res};

test('feature flags are server-authorized and mutations are role limited',async()=>{const {api,store}=setup();assert.equal((await invoke(api,{identity:'dev',path:'/api/admin/feature-flags'})).status,200);assert.equal((await invoke(api,{identity:'dev',path:'/api/admin/feature-flags',method:'POST',body:{key:'x_flag',displayName:'X'}})).status,403);assert.equal((await invoke(api,{identity:'admin',path:'/api/admin/feature-flags',method:'POST',body:{key:'x_flag',displayName:'X'}})).status,403);assert.equal((await invoke(api,{path:'/api/admin/feature-flags',method:'POST',body:{key:'x_flag',displayName:'X'}})).status,201);assert.equal(store.calls[0][0],'flag')});
test('usage and error APIs expose aggregates and sanitized metadata only',async()=>{const {api}=setup();const usage=await invoke(api,{identity:'dev',path:'/api/admin/usage?range=7d'}),errors=await invoke(api,{identity:'dev',path:'/api/admin/errors?range=7d'});assert.equal(usage.body.api_calls,12);assert.equal(errors.body.events[0].requestId,'req-safe');assert.doesNotMatch(JSON.stringify({usage:usage.body,errors:errors.body}),/prompt|token|secret|requestBody/i)});
test('invalid operational target IDs fail safely before reaching storage',async()=>{const {api}=setup();assert.equal((await invoke(api,{identity:'dev',path:'/api/admin/usage?userId=not-a-uuid'})).status,400);assert.equal((await invoke(api,{identity:'admin',path:'/api/admin/rate-limits?userId=not-a-uuid'})).status,400)});
test('notes and tags are internal mutations denied to developers',async()=>{const {api,store}=setup();const path=`/api/admin/users/${IDs.member}/notes`;assert.equal((await invoke(api,{identity:'dev',path,method:'POST',body:{note:'Follow up',category:'SUPPORT'}})).status,403);assert.equal((await invoke(api,{identity:'admin',path,method:'POST',body:{note:'Follow up',category:'SUPPORT'}})).status,201);assert.equal((await invoke(api,{identity:'admin',path:`/api/admin/users/${IDs.member}/tags/${IDs.tag}`,method:'PUT'})).status,200);assert.deepEqual(store.calls.map(c=>c[0]),['note','tag'])});
test('support mode contains explicit privacy guardrails and no session data',async()=>{const {api}=setup();const res=await invoke(api,{identity:'dev',path:`/api/admin/users/${IDs.member}/support`});assert.equal(res.status,200);assert.deepEqual(res.body.guardrails,{impersonation:false,sessionsExposed:false,rawEvidenceExposed:false});assert.doesNotMatch(JSON.stringify(res.body),/sessionToken|privateMetadata|rawEvidencePayload/)});
test('abuse controls require mutation permission and safe bounded input',async()=>{const {api,store}=setup(),body={userId:IDs.member,value:20,expiresAt:new Date(Date.now()+3600000).toISOString(),reason:'Temporary abuse response'};assert.equal((await invoke(api,{identity:'dev',path:'/api/admin/rate-limits',method:'POST',body})).status,403);assert.equal((await invoke(api,{identity:'admin',path:'/api/admin/rate-limits',method:'POST',body})).status,201);assert.equal(store.calls.at(-1)[0],'limit');assert.equal((await invoke(api,{identity:'admin',path:'/api/admin/rate-limits',method:'POST',body:{...body,value:1}})).status,400)});
test('environment and build APIs return safe metadata only',async()=>{const {api}=setup();const env=await invoke(api,{identity:'dev',path:'/api/admin/environment'}),build=await invoke(api,{identity:'dev',path:'/api/admin/build'});assert.equal(env.body.database.status,'configured');assert.equal(build.body.commitSha,'abc123');assert.doesNotMatch(JSON.stringify({env:env.body,build:build.body}),/postgres:\/\/|sk_live|secret-value/)});
