'use strict';
const content=document.querySelector('#content'),state={actor:null};
const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const adminFetch=async(path,options={})=>{const token=await window.Clerk?.session?.getToken?.();return fetch(path,{credentials:'include',...options,headers:{...(options.body?{'content-type':'application/json'}:{}),...(token?{authorization:`Bearer ${token}`} :{}),...(options.headers||{})}})};
const request=async(path,options)=>{const r=await adminFetch(path,options),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`Request failed (${r.status})`);return data};
const fmt=v=>v?new Date(v).toLocaleString():'—';
const badge=v=>`<span class="badge ${/ACTIVE|healthy/i.test(v)?'ok':/DISABLED|REVOKED|unavailable/i.test(v)?'bad':''}">${esc(v)}</span>`;
const shell=(label,title,body)=>`<p class="eyebrow">${label}</p><h1>${title}</h1>${body}`;
const showError=e=>{content.innerHTML=`<div class="error">${esc(e.message)}</div>`};
const page=location.pathname.split('/')[2]||'overview';document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===page));
const auditTable=events=>events?.length?`<table><thead><tr><th>TIME</th><th>ACTOR ROLE</th><th>ACTION</th><th>TARGET</th><th>REQUEST</th></tr></thead><tbody>${events.map(e=>`<tr><td>${fmt(e.createdAt)}</td><td>${badge(e.actorRole)}</td><td>${esc(e.action)}</td><td>${esc(e.targetType)} · ${esc(e.targetId)}</td><td class="muted">${esc(e.requestId)}</td></tr>`).join('')}</tbody></table>`:'<p class="empty">No admin activity yet.</p>';
async function overview(){const d=await request('/api/admin/overview'),c=d.counts;content.innerHTML=shell('OPERATIONS','Overview',`<div class="cards"><article class="card"><span>TOTAL USERS</span><strong>${c.totalUsers}</strong></article><article class="card"><span>ONBOARDED</span><strong>${c.onboardedUsers}</strong></article><article class="card"><span>ONBOARDING · 24H</span><strong>${c.onboardingLast24h}</strong></article><article class="card"><span>ACTIVE API KEYS</span><strong>${c.activeApiKeys??'Unavailable'}</strong></article></div><div class="panel"><h2>Recent admin activity</h2>${auditTable(d.recentActivity)}</div>`)}
function userRow(u){const owner=state.actor.role==='OWNER',canStatus=owner||(state.actor.role==='ADMIN'&&u.role==='MEMBER');return `<tr data-user="${u.id}"><td><b>${esc(u.name||'Unnamed')}</b><br><span class="muted">${esc(u.email)}</span></td><td>${owner&&u.id!==state.actor.id?`<select data-role><option>${u.role}</option>${['ADMIN','DEVELOPER','MEMBER'].filter(x=>x!==u.role).map(x=>`<option>${x}</option>`).join('')}</select>`:badge(u.role)}</td><td>${badge(u.accountStatus)}</td><td>${u.onboardingComplete?'Complete':'Incomplete'}</td><td>${fmt(u.createdAt)}</td><td>${canStatus?`<button class="action ${u.accountStatus==='ACTIVE'?'danger':''}" data-status="${u.accountStatus==='ACTIVE'?'DISABLED':'ACTIVE'}">${u.accountStatus==='ACTIVE'?'Disable':'Enable'}</button>`:'—'}</td></tr>`}
async function users(){const q=new URLSearchParams(location.search).get('q')||'',d=await request(`/api/admin/users?search=${encodeURIComponent(q)}`);content.innerHTML=shell('ACCESS CONTROL','Users',`<form class="toolbar"><input name="q" value="${esc(q)}" placeholder="Search name or email"><button class="action">Search</button></form><div class="panel"><table><thead><tr><th>USER</th><th>ROLE</th><th>STATUS</th><th>ONBOARDING</th><th>CREATED</th><th>ACTIONS</th></tr></thead><tbody>${d.users.map(userRow).join('')}</tbody></table></div>`);bindUserActions()}
function bindUserActions(){document.querySelectorAll('[data-role]').forEach(s=>s.addEventListener('change',async()=>{try{await request(`/api/admin/users/${s.closest('tr').dataset.user}/role`,{method:'PATCH',body:JSON.stringify({role:s.value})});await users()}catch(e){showError(e)}}));document.querySelectorAll('[data-status]').forEach(b=>b.addEventListener('click',async()=>{try{await request(`/api/admin/users/${b.closest('tr').dataset.user}/status`,{method:'PATCH',body:JSON.stringify({status:b.dataset.status})});await users()}catch(e){showError(e)}}))}
async function keys(){const d=await request('/api/admin/api-keys');content.innerHTML=shell('CREDENTIALS','API keys',`<div class="panel">${d.keys.length?`<table><thead><tr><th>KEY</th><th>OWNER</th><th>SCOPES</th><th>CREATED</th><th>LAST USED</th><th>STATUS</th><th></th></tr></thead><tbody>${d.keys.map(k=>`<tr><td><b>${esc(k.label)}</b><br><span class="muted">${esc(k.prefix)}</span></td><td>${esc(k.ownerName)}<br><span class="muted">${esc(k.ownerEmail)}</span></td><td>${esc((k.scopes||[]).join(', '))}</td><td>${fmt(k.createdAt)}</td><td>${fmt(k.lastUsedAt)}</td><td>${badge(k.status)}</td><td>${k.status==='ACTIVE'&&state.actor.role!=='DEVELOPER'?`<button class="action danger" data-revoke="${encodeURIComponent(k.id)}">Revoke</button>`:'—'}</td></tr>`).join('')}</tbody></table>`:'<p class="empty">No visible API keys.</p>'}</div>`);document.querySelectorAll('[data-revoke]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('Revoke this API key? This cannot be undone.'))return;try{await request(`/api/admin/api-keys/${b.dataset.revoke}/revoke`,{method:'POST'});await keys()}catch(e){showError(e)}}))}
async function audit(){const d=await request('/api/admin/audit');content.innerHTML=shell('SECURITY','Admin audit',`<div class="panel">${auditTable(d.events)}</div>`)}
async function system(){const d=await request('/api/admin/system'),rows=Object.entries(d).map(([name,v])=>`<tr><td>${esc(name)}</td><td>${badge(v.status)}</td><td class="muted">${v.latencyMs!=null?`${v.latencyMs} ms`:v.httpStatus||v.build||'—'}</td></tr>`).join('');content.innerHTML=shell('OPERATIONS','System status',`<div class="panel"><table><thead><tr><th>COMPONENT</th><th>STATUS</th><th>DETAIL</th></tr></thead><tbody>${rows}</tbody></table></div>`)}
async function start(){try{const s=await request('/api/admin/session');state.actor=s.user;document.querySelector('#actor-name').textContent=s.user.name||s.user.email;document.querySelector('#actor-role').textContent=s.user.role;const allowed=new Set(s.user.permissions);document.querySelector('[data-page="users"]').hidden=!allowed.has('user:read');document.querySelector('[data-page="api-keys"]').hidden=!allowed.has('api_key:read');await({overview,users,'api-keys':keys,audit,system}[page]||overview)()}catch(e){showError(e)}}
document.querySelector('#menu').addEventListener('click',()=>document.querySelector('.admin-shell').classList.toggle('menu-open'));
document.querySelector('#admin-sign-out').addEventListener('click',async()=>{await window.Clerk?.signOut?.();await fetch('/api/logout',{method:'POST'}).catch(()=>{});location.assign('/login')});
window.addEventListener('lians:clerk-ready',start,{once:true});if(window.__liansClerkStatus?.state==='ready')start();
